name: Build C++ Launcher for Windows

on:
  push:
    branches: [ "main", "顺序执行" ]
  pull_request:
    branches: [ "main", "顺序执行" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile resource script
      run: rc.exe launcher.rc

    # MODIFIED: Added /std:c++17 to enable modern C++ features like std::variant
    - name: Compile C++ code and link resources
      Run cl.exe /std:c++17 /EHsc /O2 /D "UNICODE" /D "_UNICODE" /utf-8 launcher.cpp launcher.res /Fe:launcher.exe /link Shlwapi.lib User32.lib ntdll.lib Shell32.lib Ole32.lib Advapi32.lib OleAut32.lib Userenv.lib

    - name: Find executable
      id: find_exe
      run: |
        $filePath = (Get-ChildItem -Recurse -Filter launcher.exe).FullName
        echo "Found executable at: $filePath"
        echo "exe-path=$filePath" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: launcher-executable
        path: ${{ steps.find_exe.outputs.exe-path }}
