name: Build C++ Launcher for Windows

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    # 新增步骤：编译资源脚本
    # rc.exe 是 Windows 资源编译器，它会将 launcher.rc 编译成 launcher.res
    - name: Compile resource script
      run: rc.exe launcher.rc

    # 修改步骤：将编译好的资源文件与C++代码一起链接
    # 我们在 cl.exe 命令中加入了 launcher.res
    - name: Compile C++ code and link resources
      run: cl.exe /EHsc /O2 /D "UNICODE" /D "_UNICODE" launcher.cpp launcher.res /Fe:launcher.exe /link Shlwapi.lib User32.lib

    - name: Find executable
      id: find_exe
      run: |
        $filePath = (Get-ChildItem -Recurse -Filter launcher.exe).FullName
        echo "Found executable at: $filePath"
        echo "exe-path=$filePath" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: launcher-executable
        path: ${{ steps.find_exe.outputs.exe-path }}
